import { db, productsTable } from "@workspace/db";
import { logger } from "./logger";

const SEED_PRODUCTS = [
  {
    id: "1",
    name: "Aura Silk Slip Dress",
    price: 350,
    originalPrice: 450,
    category: "Evening",
    image: "/images/dress1.png",
    images: ["/images/dress1.png", "/images/dress6.png"],
    isNew: true,
    isActive: true,
    description: "A whisper of silk that moves like water. The Aura Slip Dress is effortless sophistication — bias-cut to drape beautifully across every curve, finished with delicate adjustable straps and a gentle cowl neckline.",
    details: ["100% pure silk charmeuse", "Bias-cut silhouette", "Adjustable spaghetti straps", "Cowl neckline with open back", "Dry clean only", "Made in Italy"],
    sizes: ["XS", "S", "M", "L", "XL"],
    stock: 50,
  },
  {
    id: "2",
    name: "Magnolia Cream Maxi",
    price: 280,
    originalPrice: null,
    category: "Summer",
    image: "/images/dress2.png",
    images: ["/images/dress2.png", "/images/dress4.png"],
    isNew: false,
    isActive: true,
    description: "Sun-drenched and dreamy, the Magnolia Maxi is the perfect companion for warm evenings and golden afternoons.",
    details: ["60% cotton, 40% silk blend", "Relaxed maxi silhouette", "Smocked bodice with adjustable straps", "Side pockets", "Hand wash cold", "Ethically sourced fabrics"],
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    stock: 60,
  },
  {
    id: "3",
    name: "Midnight Lace Gown",
    price: 650,
    originalPrice: null,
    category: "Formal",
    image: "/images/dress3.png",
    images: ["/images/dress3.png", "/images/dress5.png"],
    isNew: false,
    isActive: true,
    description: "Drama meets refinement. The Midnight Lace Gown features intricate French lace layered over silk crepe.",
    details: ["French Chantilly lace overlay", "Silk crepe underlining", "Boned bodice with hidden zip closure", "Sweeping A-line skirt with train", "Dry clean only", "Handcrafted in France"],
    sizes: ["XS", "S", "M", "L"],
    stock: 20,
  },
  {
    id: "4",
    name: "Rosalind Floral Midi",
    price: 220,
    originalPrice: 280,
    category: "Casual",
    image: "/images/dress4.png",
    images: ["/images/dress4.png", "/images/dress2.png"],
    isNew: true,
    isActive: true,
    description: "Light as a petal and just as pretty, the Rosalind Midi is your everyday expression of femininity.",
    details: ["100% chiffon", "Wrap midi silhouette", "Floral print throughout", "Flutter sleeves", "Self-tie waist", "Gentle machine wash"],
    sizes: ["XS", "S", "M", "L", "XL"],
    stock: 80,
  },
  {
    id: "5",
    name: "Blush Structure Bodice",
    price: 450,
    originalPrice: null,
    category: "Formal",
    image: "/images/dress5.png",
    images: ["/images/dress5.png", "/images/dress3.png"],
    isNew: false,
    isActive: true,
    description: "Architectural elegance in the softest blush. This gown features a sculptural boned bodice that transitions into a fluid skirt.",
    details: ["Duchess satin bodice", "Silk chiffon skirt", "Boned and structured bodice", "Concealed back zip", "Floor-length silhouette", "Dry clean only"],
    sizes: ["XS", "S", "M", "L", "XL"],
    stock: 30,
  },
  {
    id: "6",
    name: "Champagne Wrap Dress",
    price: 310,
    originalPrice: 390,
    category: "Evening",
    image: "/images/dress6.png",
    images: ["/images/dress6.png", "/images/dress1.png"],
    isNew: false,
    isActive: true,
    description: "Understated glamour at its finest. The Champagne Wrap Dress is universally flattering.",
    details: ["Stretch satin fabric", "Wrap silhouette with adjustable tie", "Deep V-neckline", "Midi length with cascading hem", "Machine wash gentle", "Available in limited quantities"],
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    stock: 45,
  },
  {
    id: "7",
    name: "Emerald Silk Elegance",
    price: 390,
    originalPrice: null,
    category: "Evening",
    image: "/images/dress7.png",
    images: ["/images/dress7.png", "/images/dress6.png"],
    isNew: false,
    isActive: true,
    description: "A bold statement dressed in whisper-soft silk. The Emerald Evening Gown features a jewel-toned hue.",
    details: ["100% mulberry silk", "Column silhouette with front slit", "Spaghetti straps", "V-neck front and back", "Dry clean only", "Made in limited edition"],
    sizes: ["XS", "S", "M", "L"],
    stock: 15,
  },
  {
    id: "8",
    name: "Ivory Lace Bridal",
    price: 890,
    originalPrice: null,
    category: "Bridal",
    image: "/images/dress8.png",
    images: ["/images/dress8.png", "/images/dress3.png"],
    isNew: false,
    isActive: true,
    description: "Your most unforgettable moment deserves the most unforgettable gown.",
    details: ["Hand-embroidered Venetian lace", "Silk tulle underskirt", "Illusion lace neckline", "Cathedral-length train", "Boned corset bodice", "Complimentary bridal fitting included"],
    sizes: ["XS", "S", "M", "L", "XL"],
    stock: 10,
  },
  {
    id: "b1",
    name: "Rosette Mini Bag",
    price: 195,
    originalPrice: null,
    category: "Bags",
    image: "/images/bag1.png",
    images: ["/images/bag1.png"],
    isNew: true,
    isActive: true,
    description: "Bridal and soft rose mini handbag with a delicate gold chain. Perfect for elegant evenings.",
    details: ["Soft rose leather", "Gold chain strap", "Magnetic clasp", "Compact interior", "Made in Italy"],
    sizes: ["One Size"],
    stock: 40,
  },
  {
    id: "b2",
    name: "Pearl Handle Clutch",
    price: 165,
    originalPrice: null,
    category: "Bags",
    image: "/images/bag2.png",
    images: ["/images/bag2.png"],
    isNew: false,
    isActive: true,
    description: "Ivory satin clutch featuring a stunning pearl detail handle for a touch of timeless sophistication.",
    details: ["Ivory satin exterior", "Faux pearl handle", "Secure snap closure", "Silver-tone hardware", "Dust bag included"],
    sizes: ["One Size"],
    stock: 35,
  },
  {
    id: "b3",
    name: "Champagne Tote",
    price: 285,
    originalPrice: 350,
    category: "Bags",
    image: "/images/bag3.png",
    images: ["/images/bag3.png"],
    isNew: false,
    isActive: true,
    description: "A large structured champagne-colored leather tote. Spacious enough for your essentials while remaining incredibly chic.",
    details: ["Structured leather", "Champagne finish", "Spacious interior compartment", "Top handle design", "Protective feet on base"],
    sizes: ["One Size"],
    stock: 25,
  },
  {
    id: "b4",
    name: "Velvet Evening Bag",
    price: 220,
    originalPrice: null,
    category: "Bags",
    image: "/images/bag4.png",
    images: ["/images/bag4.png"],
    isNew: false,
    isActive: true,
    description: "Deep blush velvet evening bag accented with a brilliant gold clasp.",
    details: ["Deep blush velvet", "Gold-tone hardware", "Chain crossbody option", "Satin lined", "Imported"],
    sizes: ["One Size"],
    stock: 30,
  },
  {
    id: "b5",
    name: "Blush Quilted Shoulder",
    price: 340,
    originalPrice: 420,
    category: "Bags",
    image: "/images/bag5.png",
    images: ["/images/bag5.png"],
    isNew: false,
    isActive: true,
    description: "A classic reborn. Blush pink quilted leather shoulder bag offering elegance and versatility.",
    details: ["Quilted leather", "Adjustable shoulder strap", "Multiple compartments", "Turn-lock closure", "Hand finished"],
    sizes: ["One Size"],
    stock: 20,
  },
  {
    id: "b6",
    name: "Ivory Crossbody",
    price: 175,
    originalPrice: null,
    category: "Bags",
    image: "/images/bag6.png",
    images: ["/images/bag6.png"],
    isNew: false,
    isActive: true,
    description: "Minimalist ivory leather crossbody paired with gleaming gold hardware. Effortless daily luxury.",
    details: ["Smooth ivory leather", "Gold hardware accents", "Adjustable strap", "Zip closure", "Minimalist profile"],
    sizes: ["One Size"],
    stock: 50,
  },
  {
    id: "b7",
    name: "Rose Gold Chain Bag",
    price: 255,
    originalPrice: null,
    category: "Bags",
    image: "/images/bag7.png",
    images: ["/images/bag7.png"],
    isNew: true,
    isActive: true,
    description: "A rose gold chain-strap mini bag with a high-shine luxe finish to elevate any outfit.",
    details: ["Luxe metallic finish", "Rose gold tone", "Chain strap", "Evening essential", "Wipe clean"],
    sizes: ["One Size"],
    stock: 35,
  },
  {
    id: "b8",
    name: "Silk Bow Pouch",
    price: 135,
    originalPrice: 180,
    category: "Bags",
    image: "/images/bag8.png",
    images: ["/images/bag8.png"],
    isNew: false,
    isActive: true,
    description: "A beautiful cream silk evening pouch gathered with a soft ribbon bow.",
    details: ["100% Silk", "Ribbon bow detail", "Drawstring closure", "Delicate hand feel", "Special occasion piece"],
    sizes: ["One Size"],
    stock: 40,
  },
];

export async function seedProductsIfEmpty(): Promise<void> {
  try {
    const existing = await db.select().from(productsTable).limit(1);
    if (existing.length > 0) {
      logger.info("Products already seeded, skipping");
      return;
    }
    await db.insert(productsTable).values(SEED_PRODUCTS as any);
    logger.info({ count: SEED_PRODUCTS.length }, "Seeded products");
  } catch (err) {
    logger.error({ err }, "Failed to seed products");
  }
}
